import React from 'react'

const contact = () => {
  return (
    <div>
      I am a contact
    </div>
  )
}

export default contact

export const metadata = {
  title: "Contact Facebook - Connect With World",
  description: "Generated by Facebook app",
};