import React from 'react'

const about = () => {
  return (
    <div>
      I am about 
    </div>
  )
}

export default about

export const metadata = {
  title: "About Facebook - Connect With World",
  description: "Generated by Facebook app",
};